"""empty message

Revision ID: 886e3b64c14c
Revises: 9c1bba1cd21b
Create Date: 2021-04-29 16:45:32.085090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886e3b64c14c'
down_revision = '9c1bba1cd21b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_site_constraint', 'passwords', ['user_id', 'site'])
    op.create_unique_constraint(None, 'passwords', ['pid'])
    op.create_unique_constraint(None, 'users', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'passwords', type_='unique')
    op.drop_constraint('uniq_site_constraint', 'passwords', type_='unique')
    # ### end Alembic commands ###
