"""initial

Revision ID: 9ee04afa3340
Revises: 
Create Date: 2021-04-29 18:35:45.722674

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '9ee04afa3340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('master_pwd', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('passwords',
    sa.Column('pid', sqlalchemy_utils.types.uuid.UUIDType(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('user_id', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('pid'),
    sa.UniqueConstraint('user_id', 'site', name='uniq_site_constraint')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwords')
    op.drop_table('users')
    # ### end Alembic commands ###
