"""initial commit

Revision ID: c2be595a5a01
Revises: 
Create Date: 2021-09-04 14:59:57.149030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "c2be595a5a01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # initialize `pgcrypto` extension for the CRUD to work
    op.execute(text("CREATE EXTENSION IF NOT EXISTS pgcrypto;"))

    op.create_table(
        "users",
        sa.Column(
            "uid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("master_pwd", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("uid"),
    )
    op.create_table(
        "passwords",
        sa.Column(
            "pid",
            sqlalchemy_utils.types.uuid.UUIDType(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("site", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("user_id", sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("pid"),
        sa.UniqueConstraint("password"),
        sa.UniqueConstraint("pid"),
        sa.UniqueConstraint("user_id", "site", "username", name="uniq_site_username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("passwords")
    op.drop_table("users")
    # ### end Alembic commands ###
